### ISSUE TITLE
Exponential backoff

### ISSUE THREAD

**Issue by nathancmendoza** [idea-bank/ideabank-datalink#13]
Utilize exponential backoff across all DynamoDB operations.
Suggested fix: add as a decorator, so that it can be used as needed, and optionally.

**NOT** a priority

**Comment by MatthewIsayan** [comment]
[Retries via exponential backoff are built in](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/retries.html). Perhaps verify and validate it's working in the client logs.
